# Getting necessary requirements for the experiment

# Requried imports and helper function

In [26]:
IMAGE_SIZE = 256

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
!pip install lightly

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 640.7/640.7 kB 7.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 7.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.6/137.6 kB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 722.8/722.8 kB 12.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 11.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 729.2/729.2 kB 15.0 MB/s eta 0:00:00
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144552 sha256=47821727a12a88f249879e8f2bec95db99f379c2cb865186ebe97956901e67de
  Stored in directory: /root/.cache/pip/wheels/12/93/dd/1f6a127edc45659556564c5730f6d4e300888f4bca2d4c5a88
Successfully built antlr4-python3-runtime


In [3]:
!pip install git+https://github.com/PytorchLightning/lightning-bolts.git@master --upgrade

  Cloning https://github.com/PytorchLightning/lightning-bolts.git (to revision master) to /tmp/pip-req-build-p2u9bzo6
  Running command git clone --filter=blob:none --quiet https://github.com/PytorchLightning/lightning-bolts.git /tmp/pip-req-build-p2u9bzo6
  Resolved https://github.com/PytorchLightning/lightning-bolts.git to commit 4f910f6c9893eaf206eed6b7df545c8a02043a55
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.5/829.5 kB 7.9 MB/s eta 0:00:00
  Created wheel for lightning-bolts: filename=lightning_bolts-0.7.0-py3-none-any.whl size=303900 sha256=44cba743aeafdd7304eb83b7d7f7ed6a73452e61eafbe72c99f4d7418f7d2f09
  Stored in directory: /tmp/pip-ephem-wheel-cache-x80_pb60/wheels/1e/24/be/48c6a7a89feb08b86daf4b48c2b6a8fbb0bedaadbdccd1e758
Successfully built lightning-bolts
  Attempting uninstall: pytorch-lightning
    Found existing installation: pyto

In [4]:
!pip install captum

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 7.4 MB/s eta 0:00:00


In [2]:
import torch
DEVICE = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

In [3]:
import torchvision.transforms as transforms
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
from PIL import Image
import torch
import matplotlib.pyplot as plt
import numpy as np
import torchvision.transforms.functional as TF
import torch.nn.functional as F
import pl_bolts
from pl_bolts.models.autoencoders import VAE
from pl_bolts.models.self_supervised import SimCLR, SwAV
import torch.nn as nn
import torchvision

/usr/local/lib/python3.10/dist-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:34: UnderReviewWarning: The feature generate_power_seq is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  "lr_options": generate_power_seq(LEARNING_RATE_CIFAR, 11),
/usr/local/lib/python3.10/dist-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:93: UnderReviewWarning: The feature FeatureMapContrastiveTask is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  contrastive_task: Union[FeatureMapContrastiveTask] = FeatureMapCon

In [9]:
%cd /content/drive/MyDrive/Proj-DS/

/content/drive/MyDrive/Proj-DS


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [8]:
!pwd

/content


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [10]:
# Load the Explanation method
from contrastive_corpus_similarity import ContrastiveCorpusSimilarity
from rise import RISE
from utils import get_black_baseline

In [11]:
def imsc(img, *args, quiet=False, lim=None, interpolation='lanczos', **kwargs):
#for visualising images in matplotlib
    if isinstance(img, Image.Image):
        img = pil_to_tensor(img)
    handle = None
    with torch.no_grad():
        if not lim:
            lim = [img.min(), img.max()]
        img = img - lim[0]
        img.mul_(1 / (lim[1] - lim[0]))
        img = torch.clamp(img, min=0, max=1)
        if not quiet:
            bitmap = img.expand(3,
                                *img.shape[1:]).permute(1, 2, 0).cpu().numpy()
    return bitmap

# Get the models

In [28]:
from lightly.loss import NTXentLoss
from lightly.models.modules.heads import SimCLRProjectionHead
import pytorch_lightning as pl

class SimCLRModel(pl.LightningModule):
    def __init__(self):
        super().__init__()

        # create a ResNet backbone and remove the classification head
        resnet = torchvision.models.resnet18()
        self.backbone = nn.Sequential(*list(resnet.children())[:-1])

        hidden_dim = resnet.fc.in_features
        self.projection_head = SimCLRProjectionHead(hidden_dim, hidden_dim, 128)

        self.criterion = NTXentLoss()

    def forward(self, x):
        h = self.backbone(x).flatten(start_dim=1)
        z = self.projection_head(h)
        return z

    def training_step(self, batch, batch_idx):
        (x0, x1), _, _ = batch
        z0 = self.forward(x0)
        z1 = self.forward(x1)
        loss = self.criterion(z0, z1)
        self.log("train_loss_ssl", loss)
        return loss

    def configure_optimizers(self):
        optim = torch.optim.SGD(
            self.parameters(), lr=6e-2, momentum=0.9, weight_decay=5e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optim, max_epochs)
        return [optim], [scheduler]

In [29]:
#load some models

def load_supervised():
    supervised = torchvision.models.resnet50(pretrained=True)
    modules = list(supervised.children())[:-1]
    supervised = nn.Sequential(*modules, nn.Flatten()).to(DEVICE)
    supervised.eval()
    return supervised

def load_swav():
    swav_weight_path = 'https://pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar'
    swav = SwAV.load_from_checkpoint(swav_weight_path, strict=False)
    swav = swav.to(DEVICE)
    swav.eval()
    return swav


def load_simclr_custom():
    simclr = torch.load('./full_model3.pth')
    simclr.eval()
    return simclr

def load_vae():
    vae = VAE(input_height=IMAGE_SIZE).from_pretrained('stl10-resnet18')
    modules = list(vae.children())[:-3]
    vae = nn.Sequential(*modules, nn.Flatten()).to(DEVICE)
    vae.eval()
    return vae

In [30]:
def load_simclr():
    simclr_weight_path = 'https://pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt'
    simclr = SimCLR.load_from_checkpoint(simclr_weight_path, strict=False)
    simclr = simclr.to(DEVICE)
    simclr.eval()
    return simclr


In [31]:
#dowload models

load_supervised()
load_swav()
load_simclr()
load_vae()
load_simclr_custom()

print('done')

INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
Downloading: "https://pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/checkpoints/epoch%3D89.ckpt" to /root/.cache/torch/hub/checkpoints/epoch%3D89.ckpt
100%|██████████| 230M/230M [00:03<00:00, 63.4MB/s]
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded chec

done


In [32]:
def load_img_from_drive(img_name, shape=IMAGE_SIZE):
  #loads two4two images from personal drive (after they have been uploaded and unzipped)
    img = Image.open('../242/test/{}'.format(img_name)).convert('RGB')

    transform = torchvision.transforms.Compose([
        torchvision.transforms.Resize((shape, shape)),
        torchvision.transforms.ToTensor(),
        torchvision.transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                         std=[0.229, 0.224, 0.225]),
    ])

    x = transform(img).unsqueeze(0)

    return x.to(DEVICE)

In [33]:
def load_mask_from_drive(mask_name, shape=IMAGE_SIZE):
  #loads two4two masks from personal drive (after they have been uploaded and unzipped)
    mask = cv2.imread('../242/test/{}'.format(mask_name))

    target_transform = transforms.Compose([transforms.ToPILImage(), transforms.ToTensor(), torchvision.transforms.Resize((shape, shape))])
    mask = target_transform(mask).sum(dim=0).unsqueeze(dim=0)

    mask = torch.where(mask > 0, torch.tensor(1), torch.tensor(0))

    return mask

In [34]:
def to_np(x):
    return x.cpu().detach().numpy()

# Classes to perform COCOA

In [42]:
from functools import partial

get_baseline = partial(
    get_black_baseline
)



# Get data for the experiment

In [43]:
data_path = "./mixed/"

# Define the transformations to apply to the images
transform = transforms.Compose([
    transforms.Resize((256, 256)),  # Resize the images to a specific size
    transforms.ToTensor(),  # Convert the images to tensors
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                  std=[0.229, 0.224, 0.225]),

])

# Load the images from the directory using the ImageFolder dataset
dataset = ImageFolder(root=data_path, transform=transform)

# Create a data loader to iterate over the dataset in batches
batch_size = 32
data_loader_ref = DataLoader(dataset, batch_size=batch_size, shuffle=True)


In [44]:
data_path = "./noise/"

# Define the transformations to apply to the images
transform = transforms.Compose([
    transforms.Resize((256, 256)),  # Resize the images to a specific size
    transforms.ToTensor(),  # Convert the images to tensors
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                      std=[0.229, 0.224, 0.225]),
])

# Load the images from the directory using the ImageFolder dataset
dataset = ImageFolder(root=data_path, transform=transform)

# Create a data loader to iterate over the dataset in batches
batch_size = 32
data_loader_foil = DataLoader(dataset, batch_size=batch_size, shuffle=True)


In [59]:
import torch.nn as nn
import torch.nn.functional as F

import torchvision
from torchvision import transforms
from torchvision.transforms.functional import pil_to_tensor
from torchvision.transforms import ToTensor, Normalize, Resize

import tqdm.notebook as tqdm

import matplotlib.gridspec as gridspec

import numpy as np

from PIL import Image
import cv2

from matplotlib import pyplot as plt

from pl_bolts.models.self_supervised import SimCLR, SwAV
from pl_bolts.models.autoencoders import VAE

import warnings
warnings.filterwarnings("ignore")
from captum.attr import IntegratedGradients, GradientShap


In [62]:
model_super = load_supervised()
model_sim = load_simclr()
model_swav = load_swav()
model_vae = load_vae()
model_sim_custom = load_simclr_custom()

ccs_super = ContrastiveCorpusSimilarity(
        encoder=model_super.to(DEVICE),
        corpus_dataloader=data_loader_ref,
        foil_dataloader=data_loader_foil,
        normalize=True,
        batch_size=32
      )

ccs_sim = ContrastiveCorpusSimilarity(
        encoder=model_sim.to(DEVICE),
        corpus_dataloader=data_loader_ref,
        foil_dataloader=data_loader_foil,
        normalize=True,
        batch_size=32,
      )

ccs_swav = ContrastiveCorpusSimilarity(
        encoder=model_swav.to(DEVICE),
        corpus_dataloader=data_loader_ref,
        foil_dataloader=data_loader_foil,
        normalize=True,
        batch_size=32
      )

ccs_vae = ContrastiveCorpusSimilarity(
        encoder=model_vae.to(DEVICE),
        corpus_dataloader=data_loader_ref,
        foil_dataloader=data_loader_foil,
        normalize=True,
        batch_size=32
      )

ccs_sim_custom = ContrastiveCorpusSimilarity(
        encoder=model_sim_custom.to(DEVICE),
        corpus_dataloader=data_loader_ref,
        foil_dataloader=data_loader_foil,
        normalize=True,
        batch_size=32
      )

INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

In [63]:
ccs_list = [ccs_super, ccs_sim, ccs_swav, ccs_vae, ccs_sim_custom]

# RISE Experiment

In [64]:
#on Google Colab this takes a looooong time (Google kicks you out way before it finishes)
#for our 1st preliminary results we used the rolling average and let it print after every image processed
#need to do this on the TU Berlin compute cluster completly

import os

list_images = sorted(os.listdir('../242/test'))

model_name_list = ['Supervised', 'SimCLR', 'SwAV', 'VAE']#, 'Custom SimCLR']
model_list = [load_supervised, load_simclr, load_swav, load_vae]#, load_simclr_custom]
mask_bs = 100
num_batches = 30

tk_list = []
pg_list = []
rra_list = []

print(model_name_list)
#we have a total of 5k images and 5k masks for the images
#iterate over images + masks
for i in range(0,4650):
    attr_list = []
    tk_indv_list = []
    pg_indv_list = []
    rra_indiv_list = []
    image_name = list_images[i*2]
    mask_name = list_images[(i*2)+1]
    x = load_img_from_drive(image_name)
    baseline = get_baseline(x)
    mask = load_mask_from_drive(mask_name)

    #iterate over models
    for model_loader, model_name, ccs in zip(model_list, model_name_list, ccs_list):

#         model = model_loader()

        with torch.no_grad():

            rise = RISE(ccs)
            attr = rise.attribute(
                    x.cuda(),
                    (8,8),
                    baselines=baseline.cuda(),
                    mask_prob=0.5,
                    n_samples=3000,
                    normalize_by_mask_prob=True,
                )

        attr_list.append(attr)


  #iterate over models' results
    for j in range(len(model_list)):
        s=to_np(mask.squeeze())
        a=to_np(attr_list[j].mean(dim=1).cpu().detach().squeeze())

        k=1000
        #prepare shapes
        s = s.astype(bool)
        top_k_binary_mask = np.zeros(a.shape)

        #top-k intersection
        #sort and create masks
        sorted_indices = np.argsort(a, axis=None)
        np.put_along_axis(top_k_binary_mask, sorted_indices[-k:], 1, axis=None)
        top_k_binary_mask = top_k_binary_mask.astype(bool)
        tki = 1.0 / k * np.sum(np.logical_and(s, top_k_binary_mask))

        #pointing game
        #find indices with max value
        a_pg = a.copy().flatten()
        s_pg = to_np(mask.squeeze()).flatten().astype(bool)
        max_index = np.argwhere(a_pg == np.max(a_pg))
        #check if maximum of explanation is on target object class.
        hit = np.any(s_pg[max_index])

        #relevance rank accuracy
        s = to_np(mask.squeeze())
        s = np.where(s.flatten().astype(bool))[0]
        #size of the ground truth mask
        n = len(s)
        #sort in descending order
        a_sorted = np.argsort(a.flatten())[-int(n) :]
        #calculate hits
        hits = len(np.intersect1d(s, a_sorted))
        if hits != 0:
            rank_accuracy = hits / float(n)
        else:
            rank_accuracy = 0.0

        tk_indv_list.append(tki)
        pg_indv_list.append(np.float(hit))
        rra_indiv_list.append(rank_accuracy)
    tk_list.append(tk_indv_list)
    pg_list.append(pg_indv_list)
    rra_list.append(rra_indiv_list)
    if i % 1 == 0: #print rolling mean after every **1** images processed.
        print(i)
        print('Pointing Game:')
        print(np.array(pg_list).mean(axis=0))
        print('Top-K:')
        print(np.array(tk_list).mean(axis=0))
        print('Relevance Rank Acc.:')
        print(np.array(rra_list).mean(axis=0))

['Supervised', 'SimCLR', 'SwAV', 'VAE']
0
Pointing Game:
[1. 1. 1. 0.]
Top-K:
[0.579 0.877 0.941 0.   ]
Relevance Rank Acc.:
[0.41124031 0.44467054 0.62141473 0.0126938 ]


KeyboardInterrupt: ignored

# Integrated Gradients Experiment

In [66]:
#on Google Colab this takes a looooong time (Google kicks you out way before it finishes)
#for our 1st preliminary results we used the rolling average and let it print after every image processed
#need to do this on the TU Berlin compute cluster completly

# from google.colab import drive
import os

# drive.mount('/content/drive')
list_images = sorted(os.listdir('../242/test'))

model_name_list = ['Supervised', 'SimCLR', 'SwAV', 'VAE', 'Custom SimCLR']
model_list = [load_supervised, load_simclr, load_swav, load_vae, load_simclr_custom]
mask_bs = 100
num_batches = 30

tk_list = []
pg_list = []
rra_list = []

print(model_name_list)
#we have a total of 5k images and 5k masks for the images
#iterate over images + masks
for i in range(0,4650):
    attr_list = []
    tk_indv_list = []
    pg_indv_list = []
    rra_indiv_list = []
    image_name = list_images[i*2]
    mask_name = list_images[(i*2)+1]
    x = load_img_from_drive(image_name)
    baseline = get_baseline(x)
    mask = load_mask_from_drive(mask_name)

    #iterate over models
    for model_loader, model_name, ccs in zip(model_list, model_name_list, ccs_list):

        model = model_loader()

        with torch.no_grad():

            ig = IntegratedGradients(ccs)
            attr = ig.attribute(
                    x.cuda(),
                    baselines=baseline.cuda(),
                )

        attr_list.append(attr)


  #iterate over models' results
    for j in range(len(model_list)):
        s=to_np(mask.squeeze())
        a=to_np(attr_list[j].mean(dim=1).cpu().detach().squeeze())

        k=1000
        #prepare shapes
        s = s.astype(bool)
        top_k_binary_mask = np.zeros(a.shape)

        #top-k intersection
        #sort and create masks
        sorted_indices = np.argsort(a, axis=None)
        np.put_along_axis(top_k_binary_mask, sorted_indices[-k:], 1, axis=None)
        top_k_binary_mask = top_k_binary_mask.astype(bool)
        tki = 1.0 / k * np.sum(np.logical_and(s, top_k_binary_mask))

        #pointing game
        #find indices with max value
        a_pg = a.copy().flatten()
        s_pg = to_np(mask.squeeze()).flatten().astype(bool)
        max_index = np.argwhere(a_pg == np.max(a_pg))
        #check if maximum of explanation is on target object class.
        hit = np.any(s_pg[max_index])

        #relevance rank accuracy
        s = to_np(mask.squeeze())
        s = np.where(s.flatten().astype(bool))[0]
        #size of the ground truth mask
        n = len(s)
        #sort in descending order
        a_sorted = np.argsort(a.flatten())[-int(n) :]
        #calculate hits
        hits = len(np.intersect1d(s, a_sorted))
        if hits != 0:
            rank_accuracy = hits / float(n)
        else:
            rank_accuracy = 0.0

        tk_indv_list.append(tki)
        pg_indv_list.append(np.float(hit))
        rra_indiv_list.append(rank_accuracy)
    tk_list.append(tk_indv_list)
    pg_list.append(pg_indv_list)
    rra_list.append(rra_indiv_list)
    if i % 1 == 0: #print rolling mean after every **1** images processed.
        print(i)
        print('Pointing Game:')
        print(np.array(pg_list).mean(axis=0))
        print('Top-K:')
        print(np.array(tk_list).mean(axis=0))
        print('Relevance Rank Acc.:')
        print(np.array(rra_list).mean(axis=0))

['Supervised', 'SimCLR', 'SwAV', 'VAE', 'Custom SimCLR']


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

0
Pointing Game:
[0. 0. 1. 0. 0.]
Top-K:
[0.306 0.244 0.276 0.08  0.118]
Relevance Rank Acc.:
[0.22083333 0.17674419 0.16337209 0.10406977 0.16104651]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

1
Pointing Game:
[0.5 0.  1.  0.5 0.5]
Top-K:
[0.342  0.233  0.4515 0.175  0.4095]
Relevance Rank Acc.:
[0.23429054 0.18214769 0.22588138 0.17723963 0.25901425]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

2
Pointing Game:
[0.33333333 0.         1.         0.33333333 0.33333333]
Top-K:
[0.382      0.219      0.44366667 0.18833333 0.284     ]
Relevance Rank Acc.:
[0.248211   0.18369421 0.23169258 0.17334392 0.18735699]


KeyboardInterrupt: ignored

# GradientShap Experiment

In [67]:
#on Google Colab this takes a looooong time (Google kicks you out way before it finishes)
#for our 1st preliminary results we used the rolling average and let it print after every image processed
#need to do this on the TU Berlin compute cluster completly

# from google.colab import drive
import os

# drive.mount('/content/drive')
list_images = sorted(os.listdir('../242/test'))

model_name_list = ['Supervised', 'SimCLR', 'SwAV', 'VAE']#, 'Custom SimCLR']
model_list = [load_supervised, load_simclr, load_swav, load_vae]#, load_simclr_custom]
mask_bs = 100
num_batches = 30

tk_list = []
pg_list = []
rra_list = []

print(model_name_list)
#we have a total of 5k images and 5k masks for the images
#iterate over images + masks
for i in range(0,4650):
    attr_list = []
    tk_indv_list = []
    pg_indv_list = []
    rra_indiv_list = []
    image_name = list_images[i*2]
    mask_name = list_images[(i*2)+1]
    x = load_img_from_drive(image_name)
    baseline = get_baseline(x)
    mask = load_mask_from_drive(mask_name)

    #iterate over models
    for model_loader, model_name, ccs in zip(model_list, model_name_list, ccs_list):

        model = model_loader()

        with torch.no_grad():

            gs = GradientShap(ccs)
            attr = gs.attribute(
                    x.cuda(),
                    baselines=baseline.cuda(),
                    n_samples=50,
                    stdevs=0.2
                )

        attr_list.append(attr)


  #iterate over models' results
    for j in range(len(model_list)):
        s=to_np(mask.squeeze())
        a=to_np(attr_list[j].mean(dim=1).cpu().detach().squeeze())

        k=1000
        #prepare shapes
        s = s.astype(bool)
        top_k_binary_mask = np.zeros(a.shape)

        #top-k intersection
        #sort and create masks
        sorted_indices = np.argsort(a, axis=None)
        np.put_along_axis(top_k_binary_mask, sorted_indices[-k:], 1, axis=None)
        top_k_binary_mask = top_k_binary_mask.astype(bool)
        tki = 1.0 / k * np.sum(np.logical_and(s, top_k_binary_mask))

        #pointing game
        #find indices with max value
        a_pg = a.copy().flatten()
        s_pg = to_np(mask.squeeze()).flatten().astype(bool)
        max_index = np.argwhere(a_pg == np.max(a_pg))
        #check if maximum of explanation is on target object class.
        hit = np.any(s_pg[max_index])

        #relevance rank accuracy
        s = to_np(mask.squeeze())
        s = np.where(s.flatten().astype(bool))[0]
        #size of the ground truth mask
        n = len(s)
        #sort in descending order
        a_sorted = np.argsort(a.flatten())[-int(n) :]
        #calculate hits
        hits = len(np.intersect1d(s, a_sorted))
        if hits != 0:
            rank_accuracy = hits / float(n)
        else:
            rank_accuracy = 0.0

        tk_indv_list.append(tki)
        pg_indv_list.append(np.float(hit))
        rra_indiv_list.append(rank_accuracy)
    tk_list.append(tk_indv_list)
    pg_list.append(pg_indv_list)
    rra_list.append(rra_indiv_list)
    if i % 1 == 0: #print rolling mean after every **1** images processed.
        print(i)
        print('Pointing Game:')
        print(np.array(pg_list).mean(axis=0))
        print('Top-K:')
        print(np.array(tk_list).mean(axis=0))
        print('Relevance Rank Acc.:')
        print(np.array(rra_list).mean(axis=0))

['Supervised', 'SimCLR', 'SwAV', 'VAE']


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

0
Pointing Game:
[0. 1. 1. 0.]
Top-K:
[0.655 0.437 0.653 0.085]
Relevance Rank Acc.:
[0.27800388 0.22897287 0.25494186 0.10746124]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

1
Pointing Game:
[0.5 1.  1.  0.5]
Top-K:
[0.6995 0.523  0.6925 0.152 ]
Relevance Rank Acc.:
[0.29942372 0.24926326 0.27350901 0.15851154]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

2
Pointing Game:
[0.66666667 1.         0.66666667 0.33333333]
Top-K:
[0.71966667 0.56733333 0.71166667 0.16133333]
Relevance Rank Acc.:
[0.30978753 0.27428273 0.30047409 0.15676231]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

3
Pointing Game:
[0.75 1.   0.75 0.5 ]
Top-K:
[0.7425  0.5845  0.706   0.17525]
Relevance Rank Acc.:
[0.31463187 0.28299585 0.31281318 0.17029535]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

4
Pointing Game:
[0.8 1.  0.8 0.4]
Top-K:
[0.769  0.571  0.7192 0.1756]
Relevance Rank Acc.:
[0.32871994 0.27341578 0.31962642 0.16956185]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

5
Pointing Game:
[0.83333333 1.         0.83333333 0.5       ]
Top-K:
[0.773      0.5535     0.73616667 0.19383333]
Relevance Rank Acc.:
[0.32833416 0.26400221 0.32215365 0.17682744]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

6
Pointing Game:
[0.85714286 1.         0.85714286 0.57142857]
Top-K:
[0.78128571 0.55       0.73471429 0.19257143]
Relevance Rank Acc.:
[0.32816834 0.26311433 0.31544896 0.17623929]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

7
Pointing Game:
[0.875 1.    0.875 0.5  ]
Top-K:
[0.78925  0.54475  0.732375 0.195   ]
Relevance Rank Acc.:
[0.3340223  0.26066354 0.31889437 0.17985267]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

8
Pointing Game:
[0.77777778 1.         0.88888889 0.44444444]
Top-K:
[0.78666667 0.54577778 0.72544444 0.19044444]
Relevance Rank Acc.:
[0.33610462 0.2661122  0.31537417 0.18359052]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

9
Pointing Game:
[0.8 1.  0.9 0.5]
Top-K:
[0.7864 0.5443 0.7373 0.1899]
Relevance Rank Acc.:
[0.3350008  0.26290665 0.31521408 0.18002332]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

10
Pointing Game:
[0.72727273 1.         0.90909091 0.45454545]
Top-K:
[0.78872727 0.55054545 0.736      0.19054545]
Relevance Rank Acc.:
[0.33534192 0.26492493 0.31537689 0.18091485]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

11
Pointing Game:
[0.75       1.         0.91666667 0.5       ]
Top-K:
[0.7935     0.56616667 0.746      0.19208333]
Relevance Rank Acc.:
[0.33452152 0.26726272 0.31730765 0.18067395]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

12
Pointing Game:
[0.76923077 1.         0.92307692 0.53846154]
Top-K:
[0.79807692 0.57061538 0.75053846 0.18992308]
Relevance Rank Acc.:
[0.33916974 0.26921    0.31735615 0.17877437]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

13
Pointing Game:
[0.78571429 1.         0.92857143 0.57142857]
Top-K:
[0.80207143 0.57542857 0.75542857 0.19121429]
Relevance Rank Acc.:
[0.3396609  0.27055361 0.31716596 0.18019355]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

14
Pointing Game:
[0.8        1.         0.93333333 0.6       ]
Top-K:
[0.80673333 0.57373333 0.75393333 0.19073333]
Relevance Rank Acc.:
[0.34181861 0.27089603 0.31811163 0.17943184]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

15
Pointing Game:
[0.8125 0.9375 0.875  0.5625]
Top-K:
[0.803875  0.57325   0.7529375 0.188875 ]
Relevance Rank Acc.:
[0.34256045 0.2720147  0.31800495 0.18034704]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

16
Pointing Game:
[0.82352941 0.94117647 0.88235294 0.58823529]
Top-K:
[0.81458824 0.59405882 0.76635294 0.18617647]
Relevance Rank Acc.:
[0.34404813 0.27952541 0.32303973 0.17803434]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

17
Pointing Game:
[0.83333333 0.94444444 0.88888889 0.55555556]
Top-K:
[0.81366667 0.58688889 0.76227778 0.1905    ]
Relevance Rank Acc.:
[0.3448943  0.27629538 0.3207745  0.18082868]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

18
Pointing Game:
[0.84210526 0.89473684 0.89473684 0.52631579]
Top-K:
[0.81257895 0.57657895 0.76073684 0.18752632]
Relevance Rank Acc.:
[0.34481929 0.27266965 0.32089788 0.17936927]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

19
Pointing Game:
[0.85 0.9  0.9  0.55]
Top-K:
[0.81825 0.59205 0.766   0.1994 ]
Relevance Rank Acc.:
[0.34593142 0.27656677 0.32095379 0.17944346]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

20
Pointing Game:
[0.85714286 0.9047619  0.9047619  0.57142857]
Top-K:
[0.82609524 0.60571429 0.77585714 0.19747619]
Relevance Rank Acc.:
[0.347831   0.28165089 0.32418193 0.17710344]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

21
Pointing Game:
[0.86363636 0.90909091 0.90909091 0.54545455]
Top-K:
[0.82263636 0.60045455 0.76781818 0.19609091]
Relevance Rank Acc.:
[0.34699257 0.27970586 0.32135902 0.17712296]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

22
Pointing Game:
[0.86956522 0.91304348 0.91304348 0.56521739]
Top-K:
[0.82330435 0.60382609 0.75908696 0.20086957]
Relevance Rank Acc.:
[0.34636867 0.28109846 0.31846655 0.18125199]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

23
Pointing Game:
[0.875      0.91666667 0.91666667 0.54166667]
Top-K:
[0.81975    0.60420833 0.76083333 0.20266667]
Relevance Rank Acc.:
[0.34618644 0.28205542 0.3194469  0.18211698]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

24
Pointing Game:
[0.88 0.92 0.92 0.52]
Top-K:
[0.80828 0.59796 0.74776 0.20196]
Relevance Rank Acc.:
[0.34320063 0.28037272 0.31495786 0.18150302]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

25
Pointing Game:
[0.88461538 0.92307692 0.92307692 0.53846154]
Top-K:
[0.80596154 0.59911538 0.747      0.20461538]
Relevance Rank Acc.:
[0.34235647 0.28022333 0.31456815 0.183869  ]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

26
Pointing Game:
[0.88888889 0.92592593 0.92592593 0.51851852]
Top-K:
[0.80562963 0.60592593 0.74592593 0.20907407]
Relevance Rank Acc.:
[0.34178769 0.28245796 0.31364664 0.18584177]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

27
Pointing Game:
[0.89285714 0.92857143 0.92857143 0.5       ]
Top-K:
[0.80257143 0.60103571 0.74571429 0.20767857]
Relevance Rank Acc.:
[0.34051115 0.28027032 0.31481578 0.18493312]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

28
Pointing Game:
[0.89655172 0.93103448 0.93103448 0.48275862]
Top-K:
[0.80089655 0.60168966 0.74517241 0.20755172]
Relevance Rank Acc.:
[0.33950439 0.27928911 0.31363791 0.1853407 ]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

29
Pointing Game:
[0.9        0.9        0.93333333 0.5       ]
Top-K:
[0.80063333 0.60136667 0.74526667 0.21143333]
Relevance Rank Acc.:
[0.33838019 0.28053372 0.3136786  0.18818783]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

30
Pointing Game:
[0.90322581 0.90322581 0.93548387 0.51612903]
Top-K:
[0.80345161 0.60380645 0.73658065 0.21383871]
Relevance Rank Acc.:
[0.3394524  0.28158687 0.31134771 0.190172  ]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

31
Pointing Game:
[0.90625 0.90625 0.9375  0.5    ]
Top-K:
[0.7965625  0.59840625 0.7313125  0.21209375]
Relevance Rank Acc.:
[0.33774898 0.28076214 0.30895942 0.19048486]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

32
Pointing Game:
[0.90909091 0.90909091 0.93939394 0.48484848]
Top-K:
[0.79730303 0.59815152 0.73012121 0.21063636]
Relevance Rank Acc.:
[0.33802803 0.28103777 0.30905058 0.19084696]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

33
Pointing Game:
[0.91176471 0.88235294 0.94117647 0.5       ]
Top-K:
[0.79529412 0.59555882 0.72867647 0.21091176]
Relevance Rank Acc.:
[0.33770624 0.28056091 0.30859742 0.19147404]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.0 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/vae/vae-stl10/ch

34
Pointing Game:
[0.91428571 0.88571429 0.94285714 0.48571429]
Top-K:
[0.79357143 0.59497143 0.72751429 0.21108571]
Relevance Rank Acc.:
[0.33725835 0.27962092 0.30800232 0.19273862]


INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.0.4 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/bolts_simclr_imagenet/simclr_imagenet.ckpt`
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v0.9.1rc3 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file https:/pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar`


KeyboardInterrupt: ignored